import argparse
import csv
import itertools
import json
import random
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR))

import torch
import torch.nn.functional as F
from PIL import Image, ImageOps
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms

from model_components import (
    EMBEDDING_DIM,
    FASHIONCLIP_DIM,
    CLIP_MEAN,
    CLIP_STD,
    CompatibilityHead,
    build_stylist_encoder,
    build_fashionclip_encoder,
)


IMAGE_SIZE = 224
IMAGE_SUFFIXES = (".jpg", ".jpeg", ".png", ".webp")


@dataclass
class PairExample:
    left_path: Path
    right_path: Path
    label: int


@dataclass
class ResolvedItem:
    item_id: str
    path: Path
    category_id: int


class PolyvorePairDataset(Dataset):
    def __init__(self, examples, transform):
        self.examples = examples
        self.transform = transform

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, index):
        example = self.examples[index]
        left_image = load_image(example.left_path)
        right_image = load_image(example.right_path)
        label = torch.tensor(example.label, dtype=torch.float32)
        return self.transform(left_image), self.transform(right_image), label


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train a Polyvore compatibility head for the Elephante stylist API."
    )
    parser.add_argument(
        "--metadata-dir",
        type=Path,
        default=None,
        help="Directory containing the extracted xthan/polyvore-dataset metadata files (Polyvore mode).",
    )
    parser.add_argument(
        "--images-dir",
        type=Path,
        default=None,
        help="Directory containing Polyvore item images (Polyvore mode).",
    )
    parser.add_argument(
        "--pairs-csv",
        type=Path,
        default=None,
        help=(
            "CSV with columns left_path,right_path,label (0/1). "
            "Generated by fetch_fashion200k.py or fetch_pinterest_boards.py. "
            "Mutually exclusive with --metadata-dir / --images-dir."
        ),
    )
    parser.add_argument(
        "--base-model",
        type=Path,
        default=Path("elephante_stylist_brain.pt"),
        help="Existing 128-dim ResNet encoder checkpoint.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("elephante_match_head.pt"),
        help="Where to save the trained compatibility head.",
    )
    parser.add_argument("--epochs", type=int, default=5)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--hidden-dim", type=int, default=128)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--val-fraction", type=float, default=0.15)
    parser.add_argument("--pairs-per-outfit", type=int, default=12)
    parser.add_argument(
        "--example-source",
        default="category-negatives",
        choices=("category-negatives", "compatibility-file"),
        help=(
            "category-negatives builds positives from curated outfits and sampled negatives; "
            "compatibility-file uses fashion_compatibility_prediction.txt directly."
        ),
    )
    parser.add_argument(
        "--negative-ratio",
        type=int,
        default=3,
        help="Negative examples to sample for each positive pair in category-negatives mode.",
    )
    parser.add_argument(
        "--outfit-json",
        default="train_no_dup.json",
        help="Polyvore outfit JSON to use in category-negatives mode.",
    )
    parser.add_argument("--limit-examples", type=int, default=0)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--device",
        default="auto",
        choices=("auto", "cpu", "cuda", "mps"),
        help="Training device. auto prefers CUDA, then MPS, then CPU.",
    )
    parser.add_argument(
        "--fine-tune-encoder",
        action="store_true",
        help="Also update the ResNet encoder. Default only trains the compatibility head.",
    )
    parser.add_argument(
        "--encoder-output",
        type=Path,
        default=None,
        help="Optional path to save the fine-tuned encoder state dict.",
    )
    parser.add_argument(
        "--encoder",
        default="resnet50",
        choices=("resnet50", "fashionclip"),
        help=(
            "Backbone encoder to use. "
            "resnet50 (default) requires --base-model. "
            "fashionclip downloads Marqo/marqo-fashionCLIP from HuggingFace automatically."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only validate file resolution and report usable pair counts.",
    )
    return parser.parse_args()


def choose_device(name: str) -> torch.device:
    if name != "auto":
        return torch.device(name)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def load_image(path: Path) -> Image.Image:
    with Image.open(path) as image:
        return ImageOps.exif_transpose(image).convert("RGB")


def build_image_index(images_dir: Path) -> dict:
    index = {}
    for path in images_dir.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in IMAGE_SUFFIXES:
            continue

        keys = [path.stem, f"{path.parent.name}_{path.stem}"]
        for key in keys:
            index.setdefault(key, path)

    return index


def resolve_item_image(item_id: str, images_dir: Path, image_index: dict):
    indexed = image_index.get(item_id)
    if indexed is not None:
        return indexed

    set_id, _, item_index = item_id.partition("_")
    candidates = []
    for suffix in IMAGE_SUFFIXES:
        candidates.extend(
            [
                images_dir / f"{item_id}{suffix}",
                images_dir / set_id / f"{item_index}{suffix}",
                images_dir / set_id / f"{item_id}{suffix}",
            ]
        )

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return None


def read_compatibility_rows(path: Path):
    with path.open() as file:
        for line in file:
            parts = line.strip().split()
            if len(parts) < 3:
                continue
            yield int(parts[0]), parts[1:]


def item_id_for(outfit: dict, item: dict) -> str:
    return f"{outfit['set_id']}_{item['index']}"


def read_outfit_rows(path: Path):
    with path.open() as file:
        return json.load(file)


def build_resolved_outfits(metadata_dir: Path, images_dir: Path, outfit_json: str):
    outfit_path = metadata_dir / outfit_json
    if not outfit_path.exists():
        raise FileNotFoundError(f"Missing {outfit_path}")

    image_index = build_image_index(images_dir)
    category_pool = {}
    resolved_outfits = []
    skipped_outfits = 0
    missing_items = set()

    for outfit in read_outfit_rows(outfit_path):
        resolved_items = []
        for item in outfit.get("items", []):
            item_id = item_id_for(outfit, item)
            image_path = resolve_item_image(item_id, images_dir, image_index)
            if image_path is None:
                missing_items.add(item_id)
                continue

            category_id = int(item.get("categoryid", -1))
            resolved_item = ResolvedItem(item_id, image_path, category_id)
            resolved_items.append(resolved_item)
            category_pool.setdefault(category_id, []).append(resolved_item)

        if len(resolved_items) < 2:
            skipped_outfits += 1
        else:
            resolved_outfits.append(resolved_items)

    return resolved_outfits, category_pool, skipped_outfits, len(missing_items), len(image_index)


def sample_category_negative(rng, category_pool, original_item, outfit_item_ids):
    candidates = [
        item
        for item in category_pool.get(original_item.category_id, [])
        if item.item_id not in outfit_item_ids
    ]
    if not candidates:
        return None
    return rng.choice(candidates)


def build_category_negative_examples(
    metadata_dir: Path,
    images_dir: Path,
    outfit_json: str,
    pairs_per_outfit: int,
    negative_ratio: int,
    seed: int,
):
    resolved_outfits, category_pool, skipped_outfits, missing_items, indexed_images = (
        build_resolved_outfits(metadata_dir, images_dir, outfit_json)
    )

    rng = random.Random(seed)
    examples = []
    positive_count = 0
    negative_count = 0
    skipped_negatives = 0

    for outfit_items in resolved_outfits:
        outfit_item_ids = {item.item_id for item in outfit_items}
        pairs = list(itertools.combinations(outfit_items, 2))
        rng.shuffle(pairs)

        for left_item, right_item in pairs[:pairs_per_outfit]:
            examples.append(PairExample(left_item.path, right_item.path, 1))
            positive_count += 1

            for _ in range(max(0, negative_ratio)):
                replace_left = rng.random() < 0.5
                if replace_left:
                    negative_item = sample_category_negative(
                        rng,
                        category_pool,
                        left_item,
                        outfit_item_ids,
                    )
                    if negative_item is None:
                        skipped_negatives += 1
                        continue
                    examples.append(PairExample(negative_item.path, right_item.path, 0))
                else:
                    negative_item = sample_category_negative(
                        rng,
                        category_pool,
                        right_item,
                        outfit_item_ids,
                    )
                    if negative_item is None:
                        skipped_negatives += 1
                        continue
                    examples.append(PairExample(left_item.path, negative_item.path, 0))
                negative_count += 1

    stats = {
        "example_source": "category-negatives",
        "indexed_images": indexed_images,
        "positive_pairs": positive_count,
        "negative_pairs": negative_count,
        "skipped_outfits": skipped_outfits,
        "skipped_negatives": skipped_negatives,
        "missing_items": missing_items,
    }
    return examples, stats


def build_compatibility_file_examples(metadata_dir: Path, images_dir: Path, pairs_per_outfit: int, seed: int):
    compatibility_file = metadata_dir / "fashion_compatibility_prediction.txt"
    if not compatibility_file.exists():
        raise FileNotFoundError(f"Missing {compatibility_file}")

    image_index = build_image_index(images_dir)
    rng = random.Random(seed)
    examples = []
    skipped_outfits = 0
    missing_items = set()

    for label, item_ids in read_compatibility_rows(compatibility_file):
        resolved_items = []
        for item_id in item_ids:
            image_path = resolve_item_image(item_id, images_dir, image_index)
            if image_path is None:
                missing_items.add(item_id)
            else:
                resolved_items.append(image_path)

        if len(resolved_items) < 2:
            skipped_outfits += 1
            continue

        pairs = list(itertools.combinations(resolved_items, 2))
        rng.shuffle(pairs)
        for left_path, right_path in pairs[:pairs_per_outfit]:
            examples.append(PairExample(left_path, right_path, label))

    positive_count = sum(1 for example in examples if example.label == 1)
    negative_count = len(examples) - positive_count
    stats = {
        "example_source": "compatibility-file",
        "indexed_images": len(image_index),
        "positive_pairs": positive_count,
        "negative_pairs": negative_count,
        "skipped_outfits": skipped_outfits,
        "skipped_negatives": 0,
        "missing_items": len(missing_items),
    }
    return examples, stats


def build_pairs_from_csv(pairs_csv: Path) -> tuple[list, dict]:
    if not pairs_csv.exists():
        raise FileNotFoundError(f"--pairs-csv not found: {pairs_csv}")

    examples = []
    missing = []
    with pairs_csv.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            left = Path(row["left_path"])
            right = Path(row["right_path"])
            label = int(row["label"])
            if not left.exists():
                missing.append(str(left))
                continue
            if not right.exists():
                missing.append(str(right))
                continue
            examples.append(PairExample(left, right, label))

    if missing:
        print(f"  warning: {len(missing)} image paths in the CSV were not found on disk (skipped).")

    positive_count = sum(1 for e in examples if e.label == 1)
    negative_count = len(examples) - positive_count
    stats = {
        "example_source": f"csv:{pairs_csv}",
        "indexed_images": len(examples) * 2,
        "positive_pairs": positive_count,
        "negative_pairs": negative_count,
        "skipped_outfits": 0,
        "skipped_negatives": 0,
        "missing_items": len(missing),
    }
    return examples, stats


def build_pair_examples(args):
    if args.pairs_csv is not None:
        return build_pairs_from_csv(args.pairs_csv)

    if args.example_source == "compatibility-file":
        return build_compatibility_file_examples(
            args.metadata_dir,
            args.images_dir,
            args.pairs_per_outfit,
            args.seed,
        )

    return build_category_negative_examples(
        args.metadata_dir,
        args.images_dir,
        args.outfit_json,
        args.pairs_per_outfit,
        args.negative_ratio,
        args.seed,
    )


def split_examples(examples, val_fraction: float, seed: int):
    rng = random.Random(seed)
    examples = list(examples)
    rng.shuffle(examples)
    val_size = max(1, int(len(examples) * val_fraction))
    return examples[val_size:], examples[:val_size]


def make_transforms(train: bool, encoder: str = "resnet50"):
    steps = [transforms.Resize((IMAGE_SIZE, IMAGE_SIZE), antialias=True)]
    if train:
        steps.append(transforms.RandomHorizontalFlip())
    steps.append(transforms.ToTensor())
    if encoder == "fashionclip":
        steps.append(transforms.Normalize(mean=CLIP_MEAN, std=CLIP_STD))
    return transforms.Compose(steps)


def encode(encoder, images, fine_tune_encoder: bool):
    if fine_tune_encoder:
        return F.normalize(encoder(images), dim=1)

    with torch.no_grad():
        return F.normalize(encoder(images), dim=1)


def safe_divide(numerator: float, denominator: float) -> float:
    if denominator == 0:
        return 0.0
    return numerator / denominator


def binary_auc(labels, scores):
    positives = sum(labels)
    negatives = len(labels) - positives
    if positives == 0 or negatives == 0:
        return None

    ranked = sorted(zip(scores, labels), key=lambda item: item[0])
    rank_sum_positive = 0.0
    index = 0

    while index < len(ranked):
        tie_end = index + 1
        while tie_end < len(ranked) and ranked[tie_end][0] == ranked[index][0]:
            tie_end += 1

        average_rank = (index + 1 + tie_end) / 2
        positives_in_tie = sum(label for _, label in ranked[index:tie_end])
        rank_sum_positive += positives_in_tie * average_rank
        index = tie_end

    return (rank_sum_positive - positives * (positives + 1) / 2) / (positives * negatives)


def binary_metrics(labels, scores, threshold: float = 0.5) -> dict:
    predictions = [1 if score >= threshold else 0 for score in scores]

    true_positive = sum(1 for label, pred in zip(labels, predictions) if label == 1 and pred == 1)
    true_negative = sum(1 for label, pred in zip(labels, predictions) if label == 0 and pred == 0)
    false_positive = sum(1 for label, pred in zip(labels, predictions) if label == 0 and pred == 1)
    false_negative = sum(1 for label, pred in zip(labels, predictions) if label == 1 and pred == 0)

    precision = safe_divide(true_positive, true_positive + false_positive)
    recall = safe_divide(true_positive, true_positive + false_negative)
    f1 = safe_divide(2 * precision * recall, precision + recall)

    return {
        "auc": binary_auc(labels, scores),
        "accuracy": safe_divide(true_positive + true_negative, len(labels)),
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "true_positive": true_positive,
        "true_negative": true_negative,
        "false_positive": false_positive,
        "false_negative": false_negative,
    }


def format_metric(value) -> str:
    if value is None:
        return "nan"
    return f"{value:.3f}"


def summarize_metrics(prefix: str, metrics: dict) -> str:
    return (
        f"{prefix}_loss={metrics['loss']:.4f} "
        f"{prefix}_auc={format_metric(metrics['auc'])} "
        f"{prefix}_acc={metrics['accuracy']:.3f} "
        f"{prefix}_f1={metrics['f1']:.3f} "
        f"{prefix}_precision={metrics['precision']:.3f} "
        f"{prefix}_recall={metrics['recall']:.3f}"
    )


def run_epoch(encoder, head, loader, criterion, optimizer, device, fine_tune_encoder: bool):
    is_training = optimizer is not None
    head.train(is_training)
    encoder.train(is_training and fine_tune_encoder)

    total_loss = 0.0
    total_count = 0
    all_labels = []
    all_scores = []

    for left_images, right_images, labels in loader:
        left_images = left_images.to(device)
        right_images = right_images.to(device)
        labels = labels.to(device)

        if is_training:
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(is_training):
            left_embeddings = encode(encoder, left_images, fine_tune_encoder)
            right_embeddings = encode(encoder, right_images, fine_tune_encoder)
            logits = head(left_embeddings, right_embeddings)
            loss = criterion(logits, labels)

        if is_training:
            loss.backward()
            optimizer.step()

        scores = torch.sigmoid(logits).detach().cpu().tolist()
        all_scores.extend(scores)
        all_labels.extend(int(label) for label in labels.detach().cpu().tolist())
        total_loss += float(loss.item()) * labels.size(0)
        total_count += labels.size(0)

    metrics = binary_metrics(all_labels, all_scores)
    metrics["loss"] = total_loss / total_count
    return metrics


def main():
    args = parse_args()

    if args.pairs_csv is None and (args.metadata_dir is None or args.images_dir is None):
        print(
            "error: provide either --pairs-csv OR both --metadata-dir and --images-dir.",
            file=sys.stderr,
        )
        sys.exit(1)

    random.seed(args.seed)
    torch.manual_seed(args.seed)

    examples, stats = build_pair_examples(args)
    if args.limit_examples:
        examples = examples[:args.limit_examples]

    print(f"Example source: {stats['example_source']}")
    print(f"Indexed images: {stats['indexed_images']}")
    print(f"Usable pair examples: {len(examples)}")
    print(f"Positive pairs: {stats['positive_pairs']}")
    print(f"Negative pairs: {stats['negative_pairs']}")
    print(f"Skipped outfits with fewer than 2 resolved images: {stats['skipped_outfits']}")
    print(f"Skipped negatives without same-category replacement: {stats['skipped_negatives']}")
    print(f"Missing item IDs: {stats['missing_items']}")

    if args.dry_run:
        return

    if len(examples) < 10:
        raise RuntimeError("Not enough resolved Polyvore images to train.")

    train_examples, val_examples = split_examples(examples, args.val_fraction, args.seed)
    train_loader = DataLoader(
        PolyvorePairDataset(train_examples, make_transforms(train=True, encoder=args.encoder)),
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
    )
    val_loader = DataLoader(
        PolyvorePairDataset(val_examples, make_transforms(train=False, encoder=args.encoder)),
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
    )

    device = choose_device(args.device)

    if args.encoder == "fashionclip":
        print("Loading FashionCLIP encoder from HuggingFace…")
        encoder = build_fashionclip_encoder()
        embedding_dim = FASHIONCLIP_DIM
    else:
        encoder = build_stylist_encoder()
        encoder.load_state_dict(torch.load(args.base_model, map_location="cpu"))
        embedding_dim = EMBEDDING_DIM

    encoder.to(device)
    for parameter in encoder.parameters():
        parameter.requires_grad = args.fine_tune_encoder

    head_kwargs = {
        "embedding_dim": embedding_dim,
        "hidden_dim": args.hidden_dim,
        "dropout": args.dropout,
    }
    head = CompatibilityHead(**head_kwargs).to(device)

    parameters = list(head.parameters())
    if args.fine_tune_encoder:
        parameters.extend(encoder.parameters())
    optimizer = torch.optim.AdamW(parameters, lr=args.learning_rate)
    criterion = torch.nn.BCEWithLogitsLoss()

    best_val_auc = -1.0
    best_val_loss = float("inf")
    for epoch in range(1, args.epochs + 1):
        train_metrics = run_epoch(
            encoder,
            head,
            train_loader,
            criterion,
            optimizer,
            device,
            args.fine_tune_encoder,
        )
        val_metrics = run_epoch(
            encoder,
            head,
            val_loader,
            criterion,
            None,
            device,
            args.fine_tune_encoder,
        )
        print(
            f"epoch={epoch} "
            f"{summarize_metrics('train', train_metrics)} "
            f"{summarize_metrics('val', val_metrics)} "
            f"val_confusion=tp:{val_metrics['true_positive']}/"
            f"fp:{val_metrics['false_positive']}/"
            f"tn:{val_metrics['true_negative']}/"
            f"fn:{val_metrics['false_negative']}"
        )

        val_auc = val_metrics["auc"]
        should_save = False
        if val_auc is not None and val_auc > best_val_auc:
            best_val_auc = val_auc
            should_save = True
        elif val_auc is None and val_metrics["loss"] < best_val_loss:
            should_save = True

        if should_save:
            best_val_loss = val_metrics["loss"]
            source = str(args.pairs_csv) if args.pairs_csv else "xthan/polyvore-dataset"
            checkpoint = {
                "state_dict": head.state_dict(),
                "head_kwargs": head_kwargs,
                "encoder_type": args.encoder,
                "source": source,
                "example_source": stats["example_source"],
                "negative_ratio": getattr(args, "negative_ratio", None),
                "outfit_json": getattr(args, "outfit_json", None),
                "epoch": epoch,
                "selection_metric": "auc" if val_auc is not None else "loss",
                "train_metrics": train_metrics,
                "val_metrics": val_metrics,
            }
            torch.save(checkpoint, args.output)
            print(f"saved {args.output}")

    if args.fine_tune_encoder and args.encoder_output is not None:
        torch.save(encoder.state_dict(), args.encoder_output)
        print(f"saved {args.encoder_output}")


if __name__ == "__main__":
    main()
